/*Confirming the number of births for mothers using POB for 99-11*/

LIBNAME VA 'C:\Users\njain\Documents\Personal\Dissertation\Data_NJ\ALLBIRTHS_SASDATA';
LIBNAME NJ 'C:\Users\njain\Documents\Personal\Dissertation\Data_NJ\Final_data\Individual datafiles';

DATA VA.ALLBIRTH1999_2011;
	SET VA.birth_1999
		VA.birth_2000
		VA.birth_2001
		VA.birth_2002
		VA.birth_2003
		VA.birth_2004
		VA.birth_2005
		VA.birth_2006
		VA.birth_2007
		VA.birth_2008
		VA.birth_2009
		VA.birth_2010
		VA.birth_2011;

KEEP B_STATE CHILD_DOB CHILD_YOB Child_LName Child_SName Child_FName Child_MName Sex M_MNAME M_FNAME M_MIDDLE M_MNAME M_DOB M_POB 
	 F_DOB F_BIR_PL M_RACE F_RACE M_HISP F_HISP M_EDU F_EDU LMP CLIN_EST_GEST BWT_UNIT BWT YOBC YOBM YOBF;

RUN;
DATA TEMP_NONNJ;
	SET VA.ALLBIRTH1999_2011;
	IF M_POB EQ '31' AND B_STATE EQ '31';
RUN;
DATA VA.MATCH9911_NONNJ;
	SET VA.ALLBIRTH1999_2011;
	IF M_POB NE '31';
RUN;
PROC FREQ DATA = VA.MATCH9911_NONNJ;
TABLES B_STATE;
RUN;

DATA BIRTHPLACE;
	SET VA.ALLBIRTH1999_2011;

	IF M_POB EQ "31" AND 1998 > YOBC < 9999 THEN BIRTH_NJ = 0;
	ELSE BIRTH_NJ = 1;

	IF M_POB EQ "31" THEN BIRTH_MOM_NJ = 0;
	ELSE BIRTH_MOM_NJ = 1;

RUN;

PROC FREQ DATA = BIRTHPLACE;
TABLES YOBC*BIRTH_MOM_NJ;
RUN;

DATA BIRTHNJ;
	SET NJ.COHORT_9911;

	IF M_POB EQ "31" THEN MOM_NJ = 0;
	ELSE MOM_NJ = 1;

RUN;
PROC FREQ DATA = NJ.COHORT_9911;;
TABLES m_pob;

RUN;
